Add readme.md
peteronyam/Hello-Microverse-Project pull request #1
Opened 2023-02-14 21:57 UTC by peteronyam

Add readme

2023-02-14 23:10 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @peteronyam, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

- [ ] You did a great job using the Microverse README template! 💯 However, please make sure that you remove the guiding comments from all sections! as they serve as just boilerplate text so you have an idea of what to include in each section! 🤓 (Image only shows 3).

![imageedit_4_9524725346](https://user-images.githubusercontent.com/77069011/218880258-a56142cc-ce43-4aad-98f2-f943b081e8de.gif)


- [ ] Please consider including some content in your "Getting started" section, this is one of the most important ones for collaboration! Here you guide other devs on how they can get a local copy of the project up and running. 🤓 🔧 

![image](https://user-images.githubusercontent.com/77069011/218882656-cf9d0bb1-e175-4eee-9e35-84fbf2c00f53.png)

- [ ] Please consider editing your PR description including detailed information about what you're adding to the project in this Pull request. ⚠️ **Also, for future projects, please avoid naming your branch "feature", instead, use the actual name of the feature you're implementing, in this case, it could be "hello-microverse". PLEASE DO NOT ATTEMPT TO CHANGE IT HERE SINCE IT CAN CAUSE SOME UNEXPECTED ISSUES WITH YOUR COMMIT HISTORY.** ⚠️ 🤓 

![imageedit_7_8644075940](https://user-images.githubusercontent.com/77069011/218883450-3313ed89-211a-43f1-bf0c-8ea321ff7b36.gif)

- [ ] According to the requirements, you should have a `.gitignore` file with the `node_modules` in it:

![image](https://user-images.githubusercontent.com/77069011/218883639-c7432cda-a481-460c-9c8d-085f0a372400.png)

- [ ] Also, there's a task that requires you to create a `test.md` file and make sure it's ignored by git. However, I'm unable to see this. Please consider doing it! 🤓 🔧 

![image](https://user-images.githubusercontent.com/77069011/218883709-8daccc87-abb4-43c3-a33c-3407de33d372.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 15:27 UTC, Kamba56 requested changes
Hi @peteronyam, 

Great work on making the changes requested by a previous reviewer 👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Great use of Github workflow!👏👏👏
- [x] All linters passed!👏👏👏

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 15:27 UTC, Kamba56 commented on README.md
>  ## 💻 Getting Started <a name="getting-started"></a>
- [ ] As requested by the previous reviewer, kindly fill in all the necessary sub sections under the getting started section. The prerequisites are those things a user will reuwire before they can clone your project. You add a comment to clone under the `clone this repo with:` etc.

2023-02-15 15:48 UTC, peteronyam commented
Please, my coding partner submitted this readme template just the way it is
yesterday without making changes to the comments sections at all he only
added his usernames where we were required to add our social profile and
that’s it, why am I passing through this, please
Plus the fact that I have only one time left to submit this project for
review

On Wed, 15 Feb 2023 at 9:27 AM, Toma John Musa ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @peteronyam <https://github.com/peteronyam>,
>
> Great work on making the changes requested by a previous reviewer 👏!👏👏
> 👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
> Highlights
>
>    - Great use of Github workflow!👏👏👏
>    - All linters passed!👏👏👏
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/peteronyam/Hello-Microverse-Project/pull/1#discussion_r1107275447>
> :
>
> > @@ -117,9 +112,7 @@ After you're finished please remove all the comments and instructions!
>
>  <!-- GETTING STARTED -->
>
>
>
>  ## 💻 Getting Started <a name="getting-started"></a>
>
>
>
>    - As requested by the previous reviewer, kindly fill in all the
>    necessary sub sections under the getting started section. The prerequisites
>    are those things a user will reuwire before they can clone your project.
>    You add a comment to clone under the clone this repo with: etc.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/peteronyam/Hello-Microverse-Project/pull/1#pullrequestreview-1299722899>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHNS3YF5E5L3R4LIS6OD5R3WXTYXNANCNFSM6AAAAAAU4C73NM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-15 17:09 UTC, peteronyam commented
Can you please, check that now
I have made the changes as required
Plus I only have one time left to submit this for review please

2023-02-15 19:03 UTC, Gambit142 requested changes
Hi @peteronyam 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- All linters checks passed ✔️ 
- `README.md` file is professional ✔️ 
- `node_modules` and the `test.md` file were git ignored ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Required Changes ♻️
- [ ]  The first reviewer requested that you edit the pull request summary. Kindly edit your pull request summary and describe/summarize what you did in this project. Pull request summaries help reviewers in the professional world have an idea of what changes were introduced in a feature branch

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 19:04 UTC, Gambit142 commented
> Can you please, check that now I have made the changes as required Plus I only have one time left to submit this for review please

Great work @peteronyam, the only thing you need to do is edit your pull request summary. 👍

2023-02-15 19:36 UTC, peteronyam commented
> > Can you please, check that now I have made the changes as required Plus I only have one time left to submit this for review please
> 
> 
> 
> Great work @peteronyam, the only thing you need to do is edit your pull request summary. 👍 

I have added the message, please help review it, you know that was my last review request, please I have done everything.

2023-02-15 19:46 UTC, Gambit142 commented
> > > Can you please, check that now I have made the changes as required Plus I only have one time left to submit this for review please
> > 
> > 
> > Great work @peteronyam, the only thing you need to do is edit your pull request summary. 👍
> 
> I have added the message, please help review it, you know that was my last review request, please I have done everything.

Hi @peteronyam, you are good to go. You have edited the pull request summary. Great work 👏

2023-02-15 19:55 UTC, peteronyam commented
> > > > Can you please, check that now I have made the changes as required Plus I only have one time left to submit this for review please
> 
> > > 
> 
> > > 
> 
> > > Great work @peteronyam, the only thing you need to do is edit your pull request summary. 👍
> 
> > 
> 
> > I have added the message, please help review it, you know that was my last review request, please I have done everything.
> 
> 
> 
> Hi @peteronyam, you are good to go. You have edited the pull request summary. Great work 👏 

Why is it still showing "pending review" ?

2023-02-15 20:01 UTC, souad988 approved these changes
Hi @peteronyam , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
- Try to use a short PR summary that describes the work done in the feature. 
   
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 20:15 UTC, peteronyam commented
Merging pull requests from the feature branch to the main branch

2023-02-15 20:15 UTC, merged